#####################################################################
# Livingroom light
#####################################################################
- id: lights_on_when_home
  alias: Lights on when I get home
  trigger:
  - platform: zone
    entity_id: device_tracker.mi5_gemini
    zone: zone.home
    event: enter
  condition:
    condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
  - service: light.turn_on
    entity_id: light.yeelight_rgb_f0b429a81a2a
  # - service: notify.telegram
  #   data:
  #     message: '[Automation] Lights on when I get home'

- id: toggle_livingroom_light
  alias: Toggle livingroom light
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0000ed5140
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.yeelight_rgb_f0b429a81a2a

- id: change_brightness
  alias: Change livingroom light brightness
  trigger:
    platform: event
    event_type: cube_action
    event_data:
        entity_id: binary_sensor.cube_158d000101af4f
        action_type: rotate
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.yeelight_rgb_f0b429a81a2a
        brightness: >
                      {% set state = states.light.yeelight_rgb_f0b429a81a2a.attributes.brightness + (trigger.event.data.action_value|float) -%}
                      {%-  if state > 255 -%}
                         {%- set state  = 255 -%}
                      {%-  elif state < 0 -%}
                         {%- set state  = 0 -%}
                      {%- endif %}
                      {{ state|round }}

#####################################################################
# All lights
#####################################################################
- id: lights_off_when_away
  alias: Lights off when I leave home
  trigger:
  - platform: zone
    entity_id: device_tracker.mi5_gemini
    zone: zone.home
    event: leave
  action:
  - service: light.turn_off
    entity_id: group.all_lights
  # - service: notify.telegram
  #   data:
  #     message: '[Automation] Lights off when I leave home'

- id: lights off
  alias: Turn off all lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0000eff014
      click_type: single
  action:
    - service: light.turn_off
      entity_id: group.all_lights

#####################################################################
# Bathroom light
#####################################################################
- id: bathroom_light_on
  alias: If there is motion turn on the bathroom light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0000f195b0
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.yeelight_white_f0b4290ecca9
    data:
      brightness: 100

- id: bathroom_light_off
  alias: If there no motion for 5 minutes turn off the bathroom light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0000f195b0
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.yeelight_white_f0b4290ecca9

#####################################################################
# System
#####################################################################
# - id: renew_ssl
#   alias: 'Auto Renew SSL Cert'
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.ssl_cert_expiry
#     below: 29
#   action:
#     service: shell_command.renew_ssl

# - id: renew_ssl
#   alias: 'SSL expiry notification'
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.ssl_cert_expiry
#     below: 21
#   action:
#     service: notify.telegram
#     data:
#       message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'
